using Microsoft.AspNetCore.Mvc;

namespace IntelliOpsAI.Controllers
{
    public class AIReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Generate()
        {
            // Simulated AI logic (we will upgrade later with real API)
            string report = GenerateAIReport();

            ViewBag.Report = report;

            return View("Index");
        }

        private string GenerateAIReport()
        {
            return "AI Analysis Report\n\n" +
                   "1. Overall productivity is stable.\n" +
                   "2. Task completion rate is within expected range.\n" +
                   "3. Peak efficiency observed in morning hours.\n" +
                   "4. Workload distribution can be improved.\n" +
                   "5. Recommendation: optimize task balancing across employees.\n\n" +
                   "Generated by IntelliOps AI System (Prototype)";
        }
    }
}